// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/jwt/check": {
            "get": {
                "security": [
                    {
                        "jwt-access": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jwt-check"
                ],
                "responses": {
                    "200": {
                        "description": "comment",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-login"
                ],
                "parameters": [
                    {
                        "description": "User Info Body",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/common.LoginInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.LoginResult"
                        }
                    }
                }
            }
        },
        "/api/refresh": {
            "get": {
                "security": [
                    {
                        "jwt-refresh": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jwt-refresh"
                ],
                "responses": {
                    "200": {
                        "description": "comment",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.LoginInfo": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "common.LoginResult": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "email_agree": {
                    "type": "boolean"
                },
                "jwt": {
                    "$ref": "#/definitions/jwt.TokenDetails"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "sms_agree": {
                    "type": "boolean"
                },
                "status": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "jwt.TokenDetails": {
            "type": "object",
            "properties": {
                "accesstoken": {
                    "type": "string"
                },
                "accessuuid": {
                    "type": "string"
                },
                "atexpires": {
                    "type": "integer"
                },
                "refreshtoken": {
                    "type": "string"
                },
                "refreshuuid": {
                    "type": "string"
                },
                "rtexpires": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "jwt-access": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "jwt-refresh": {
            "type": "apiKey",
            "name": "Refresh_Token",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:4000",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Swagger Example API",
	Description: "This is a sample server Petstore server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
